title: "Wadika Faisal"
description: "Process Improvement Engineer (EIT) | M.Eng Student | Founder of EmpowerHer Lab"
theme: jekyll-theme-minimal
show_downloads: false

author:
  name: "Wadika Faisal"
  email: ""
  linkedin: "https://www.linkedin.com/your-link"
  github: "https://github.com/your-username"
  location: "Toronto, Canada"

markdown: kramdown
